# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintrust_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='chat_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='username',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='chatmember',
            unique_together=set([('username', 'chat_id')]),
        ),
    ]
