# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintrust_bot', '0002_auto_20160506_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('quotes_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('text', models.TextField(max_length=500)),
                ('context', models.TextField(blank=True, max_length=500)),
                ('author', models.TextField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
