# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintrust_bot', '0003_quotechat_quotestorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotechat',
            name='chat_id',
            field=models.IntegerField(unique=True),
        ),
    ]
