# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintrust_bot', '0006_auto_20160703_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotestorage',
            name='location',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
