# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-10 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintrust_bot', '0008_quotestorage_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('sender', models.TextField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photo_id', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
