# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-10 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintrust_bot', '0009_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='sender_username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
