# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-19 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintrust_bot', '0010_photo_sender_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='EightBallAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('chat_id', models.BigIntegerField()),
            ],
        ),
    ]
