# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintrust_bot', '0011_eightballanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuiplashPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('sender_username', models.TextField(blank=True, max_length=100, null=True)),
                ('chat_id', models.BigIntegerField()),
            ],
        ),
    ]
