# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-29 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('braintrust_bot', '0012_quiplashprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alexa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='quotechat',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alexa',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='braintrust_bot.QuoteChat'),
        ),
    ]
